apiVersion: v2
name: "google-cloudrun-starter"
description: A starter Helmless application chart for Google Cloud Run.
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: google-cloudrun-service
    version: 0.2.1
    repository: oci://ghcr.io/helmless
    alias: service
  - name: google-cloudrun-job
    version: 0.1.1
    repository: oci://ghcr.io/helmless
    alias: job
